- src: geerlingguy.php
  version: 1.6.7

#- src: DavidWittman.redis
#  version: 1.0.2

- src: geerlingguy.varnish
  version: 1.1.1

- src: geerlingguy.java
  version: 1.1.0

- src: JasonGiedymin.nodejs
  version: master

- src: kosssi.composer
  version: master

- src: greendayonfire.mongodb
  version: v1.2.2

- src: alban.andrieu.jmeter
  version: master

- src: clickfreak.elasticsearch
  version: master
