---
- hosts: webserver
  sudo: yes
  roles:
    - users
    - php
    - web
    - git
    - orchestraCron
- hosts: database
  sudo: yes
  roles:
    - databases
- hosts: test
  sudo: yes
  roles:
    - selenium
    - jmeter
