---
- name: Download chrome driver if not installed
  get_url: url={{download_driver}} dest={{selenium_current_directory}}/{{driver}} force=no

- name: Install unzip if not installed
  apt: name=unzip state=present

- name: Unzip chrome driver
  unarchive: src={{selenium_current_directory}}/{{driver}} dest={{selenium_current_directory}} copy=no

- name: Put chrome driver runable
  shell: chmod +x {{selenium_current_directory}}/{{driver_exec}}
