---
- name: Check firefox exist
  stat: path=/opt/{{firefox_name}}
  register: package

- name: Download firefox if not installed
  get_url: url={{firefox_url}} dest={{selenium_current_directory}}
  when: package.stat.exists == False

- name: Unarchive firefox
  shell: tar -xjvf {{selenium_current_directory}}/{{firefox_package}}
  when: package.stat.exists == False

- name: Move firefox
  shell: mv firefox /opt/{{firefox_name}}
  when: package.stat.exists == False

- name: Firefox symbolic link
  file: src=/opt/{{firefox_name}}/firefox dest=/usr/bin/firefox state=link
  when: package.stat.exists == False
