---
- name: check to make sure sudo is installed
  apt:
    pkg=sudo state=present update_cache=yes
  tags: sudo
 
- name: configure sudoers
  lineinfile: dest=/etc/sudoers.d/{{item}} owner=root group=root mode=0440
              line="{{item}} ALL=(ALL) NOPASSWD:/usr/sbin/service"
              state=present
              create=yes
              validate='visudo -cf %s'
  with_items: sudoers