---
 - name: ensure apache is at the latest version
   apt: pkg=apache2 state=latest
 - name: ensure apache is running
   service: name=apache2 state=started
 - name: ensure ssl mod is loaded
   apache2_module: state=present name=ssl
 - name: ensure rewrite mod is loaded
   apache2_module: state=present name=rewrite
