---
# basic system packages installation
- name: apt - install basic system packages
  apt: name={{item}} state=latest update-cache=yes cache_valid_time=3600
  with_items:
    - curl
    - git
    - g++
    - gcc # to make install
    - ifupdown-extra
    - iotop
    - libfontconfig1
    - lynx
    - make
    - netcat-openbsd
    - ntp
    - python-pycurl # needed by ansible module apt_repository
    - socat
    - strace
    - sysstat
    - tig
    - tree
    - tzdata
    - vim
