---
 - name: Check if file apache redis exists
   stat: path=/etc/php5/cli/conf.d/30-redis.ini
   register: cli_redis
 - name: Create symbolic link redis.ini
   file: src=/etc/php5/mods-available/redis.ini dest=/etc/php5/cli/conf.d/30-redis.ini state=link
   when: cli_redis.stat.exists == false
