---
 - name: Install php-redis extension
   shell: pecl install redis
   register: pecl_redis_result
   failed_when: pecl_redis_result.rc > 1
   changed_when: "'pecl/redis is already installed' not in pecl_redis_result.stdout"
 - name: Check redis conf file
   stat: path=/etc/php5/mods-available/redis.ini
   register: redis_conf
 - name: Create the redis extension
   shell: echo "extension=redis.so" > /etc/php5/mods-available/redis.ini
   when: redis_conf.stat.exists == false
