---
sitemap_minute: 0
sitemap_hour: 2
sitemap_task: "{{command_php}} {{path_front}}/app/console {{sitemap_command}} 2>> {{error_file}}"
sitemap_command: "-e={{env}} orchestra:sitemaps:generate"

robots_minute: 0
robots_hour: 2
robots_task: "{{command_php}} {{path_front}}/app/console {{robots_command}} 2>> {{error_file}}"
robots_command: "-e={{env}} orchestra:robots:generate"

mail_minute: 59
mail_hour: 0-23
mail_task: "if [ -s '{{error_file}}' ]; then  cat {{error_file}} | {{sendmail_command}} fi; rm {{error_file}};"
sendmail_command: mailx -s \"cron error\" {{notification_mail}};
notification_mail: 'contact@open-orchestra.com'

env: prod
command_php: php
error_file: /tmp/cron.error.message
