---
sitemap_minute: 0
sitemap_hour: 2
sitemap_task: '{{command_php}} {{path_front}}/app/console {{sitemap_command}} {{rm_stdout}}'
sitemap_command: "-e={{env}} orchestra:sitemaps:generate"

robots_minute: 0
robots_hour: 2
robots_task: '{{command_php}} {{path_front}}/app/console {{robots_command}} {{rm_stdout}}'
robots_command: "-e={{env}} orchestra:robots:generate"

cron_file: open-orchestra
cron_user: root
rm_stdout: 1> /dev/null

env: prod
command_php: php
